name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore .NET dependencies
      run: dotnet restore OrderService.Tests/OrderService.Tests.csproj

    - name: Build .NET project
      run: dotnet build OrderService.Tests/OrderService.Tests.csproj --configuration Release --no-restore

    - name: Run .NET unit tests
      run: dotnet test OrderService.Tests/OrderService.Tests.csproj --configuration Release --no-restore
